CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, google_id TEXT UNIQUE NOT NULL, email TEXT UNIQUE NOT NULL, name TEXT, avatar_url TEXT, created_at INTEGER NOT NULL, last_login_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS user_sessions (token TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS organizations (id TEXT PRIMARY KEY, slug TEXT UNIQUE NOT NULL, name TEXT NOT NULL, owner_user_id TEXT NOT NULL, created_at INTEGER NOT NULL, FOREIGN KEY(owner_user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS subscriptions (id TEXT PRIMARY KEY, org_id TEXT NOT NULL, plan_tier TEXT NOT NULL, status TEXT NOT NULL, max_workspaces INTEGER NOT NULL, max_devices INTEGER NOT NULL, max_dashboards INTEGER NOT NULL, current_period_end INTEGER NOT NULL, created_at INTEGER NOT NULL, FOREIGN KEY(org_id) REFERENCES organizations(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS organization_members (org_id TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY (org_id, user_id), FOREIGN KEY(org_id) REFERENCES organizations(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS workspaces (id TEXT PRIMARY KEY, org_id TEXT NOT NULL, slug TEXT NOT NULL, name TEXT NOT NULL, description TEXT, created_at INTEGER NOT NULL, UNIQUE (org_id, slug), FOREIGN KEY(org_id) REFERENCES organizations(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS devices (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, name TEXT NOT NULL, role TEXT DEFAULT 'primary', priority INTEGER DEFAULT 100, key_hash TEXT UNIQUE NOT NULL, key_prefix TEXT NOT NULL, tunnel_url TEXT, tunnel_mode TEXT DEFAULT 'quick', routing_mode TEXT DEFAULT 'proxy', is_online INTEGER DEFAULT 0, app_version TEXT, os_info TEXT, last_heartbeat_at INTEGER, created_at INTEGER NOT NULL, FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS dashboards (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, name TEXT NOT NULL, slug TEXT NOT NULL, is_public INTEGER DEFAULT 0, created_at INTEGER NOT NULL, FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS dashboard_permissions (dashboard_id TEXT NOT NULL, user_id TEXT NOT NULL, permission TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY (dashboard_id, user_id), FOREIGN KEY(dashboard_id) REFERENCES dashboards(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id TEXT NOT NULL, user_id TEXT, device_id TEXT, event TEXT NOT NULL, ip_address TEXT, details TEXT, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON user_sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_sub_org ON subscriptions(org_id);
CREATE INDEX IF NOT EXISTS idx_org_slug ON organizations(slug);
CREATE INDEX IF NOT EXISTS idx_ws_org ON workspaces(org_id);
CREATE INDEX IF NOT EXISTS idx_ws_org_slug ON workspaces(org_id, slug);
CREATE INDEX IF NOT EXISTS idx_dev_ws ON devices(workspace_id);
CREATE INDEX IF NOT EXISTS idx_dev_key ON devices(key_hash);
CREATE INDEX IF NOT EXISTS idx_dsh_ws ON dashboards(workspace_id);
CREATE INDEX IF NOT EXISTS idx_dsh_perm ON dashboard_permissions(dashboard_id);
CREATE INDEX IF NOT EXISTS idx_dev_heartbeat ON devices(last_heartbeat_at);
